// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: commonVote.proto

package advicepb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AddVoteResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AddVoteResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddVoteResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddVoteResponseMultiError, or nil if none found.
func (m *AddVoteResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AddVoteResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for NewRating

	// no validation rules for RemainingPaidVotes

	// no validation rules for SilentPush

	if len(errors) > 0 {
		return AddVoteResponseMultiError(errors)
	}

	return nil
}

// AddVoteResponseMultiError is an error wrapping multiple validation errors
// returned by AddVoteResponse.ValidateAll() if the designated constraints
// aren't met.
type AddVoteResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddVoteResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddVoteResponseMultiError) AllErrors() []error { return m }

// AddVoteResponseValidationError is the validation error returned by
// AddVoteResponse.Validate if the designated constraints aren't met.
type AddVoteResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddVoteResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddVoteResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddVoteResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddVoteResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddVoteResponseValidationError) ErrorName() string { return "AddVoteResponseValidationError" }

// Error satisfies the builtin error interface
func (e AddVoteResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddVoteResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddVoteResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddVoteResponseValidationError{}
