// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: getAdvices.proto

package advicepb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetAdvicesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAdvicesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAdvicesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAdvicesResponseMultiError, or nil if none found.
func (m *GetAdvicesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAdvicesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetAdvices() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetAdvicesResponseValidationError{
						field:  fmt.Sprintf("Advices[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetAdvicesResponseValidationError{
						field:  fmt.Sprintf("Advices[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetAdvicesResponseValidationError{
					field:  fmt.Sprintf("Advices[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetAdvicesResponseMultiError(errors)
	}

	return nil
}

// GetAdvicesResponseMultiError is an error wrapping multiple validation errors
// returned by GetAdvicesResponse.ValidateAll() if the designated constraints
// aren't met.
type GetAdvicesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAdvicesResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAdvicesResponseMultiError) AllErrors() []error { return m }

// GetAdvicesResponseValidationError is the validation error returned by
// GetAdvicesResponse.Validate if the designated constraints aren't met.
type GetAdvicesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAdvicesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAdvicesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAdvicesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAdvicesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAdvicesResponseValidationError) ErrorName() string {
	return "GetAdvicesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetAdvicesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAdvicesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAdvicesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAdvicesResponseValidationError{}

// Validate checks the field values on Advices with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Advices) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Advices with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in AdvicesMultiError, or nil if none found.
func (m *Advices) ValidateAll() error {
	return m.validate(true)
}

func (m *Advices) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Screen

	if all {
		switch v := interface{}(m.GetContent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AdvicesValidationError{
					field:  "Content",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AdvicesValidationError{
					field:  "Content",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetContent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AdvicesValidationError{
				field:  "Content",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetDeepLink()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AdvicesValidationError{
					field:  "DeepLink",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AdvicesValidationError{
					field:  "DeepLink",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDeepLink()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AdvicesValidationError{
				field:  "DeepLink",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AdvicesMultiError(errors)
	}

	return nil
}

// AdvicesMultiError is an error wrapping multiple validation errors returned
// by Advices.ValidateAll() if the designated constraints aren't met.
type AdvicesMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AdvicesMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AdvicesMultiError) AllErrors() []error { return m }

// AdvicesValidationError is the validation error returned by Advices.Validate
// if the designated constraints aren't met.
type AdvicesValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AdvicesValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AdvicesValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AdvicesValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AdvicesValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AdvicesValidationError) ErrorName() string { return "AdvicesValidationError" }

// Error satisfies the builtin error interface
func (e AdvicesValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAdvices.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AdvicesValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AdvicesValidationError{}
