// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: setReferral.proto

package advicepb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SetReferralRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SetReferralRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetReferralRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SetReferralRequestMultiError, or nil if none found.
func (m *SetReferralRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SetReferralRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() <= 0 {
		err := SetReferralRequestValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetReferralCode()); l < 1 || l > 50 {
		err := SetReferralRequestValidationError{
			field:  "ReferralCode",
			reason: "value length must be between 1 and 50 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetPetId() <= 0 {
		err := SetReferralRequestValidationError{
			field:  "PetId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return SetReferralRequestMultiError(errors)
	}

	return nil
}

// SetReferralRequestMultiError is an error wrapping multiple validation errors
// returned by SetReferralRequest.ValidateAll() if the designated constraints
// aren't met.
type SetReferralRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetReferralRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetReferralRequestMultiError) AllErrors() []error { return m }

// SetReferralRequestValidationError is the validation error returned by
// SetReferralRequest.Validate if the designated constraints aren't met.
type SetReferralRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetReferralRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetReferralRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetReferralRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetReferralRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetReferralRequestValidationError) ErrorName() string {
	return "SetReferralRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SetReferralRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetReferralRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetReferralRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetReferralRequestValidationError{}
