// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// protoc-gen-go-micro version: v3.10.15
// source: adviceService.proto

package advicepb

import (
	context "context"
	_go "github.com/megauspexx/petsvote.last-proto/go"
	client "go.unistack.org/micro/v3/client"
	server "go.unistack.org/micro/v3/server"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

type adviceServiceClient struct {
	c    client.Client
	name string
}

func NewAdviceServiceClient(name string, c client.Client) _go.AdviceServiceClient {
	return &adviceServiceClient{c: c, name: name}
}

func (c *adviceServiceClient) CreateAdvices(ctx context.Context, req *_go.CreateAdvicesRequest, opts ...client.CallOption) (*emptypb.Empty, error) {
	rsp := &emptypb.Empty{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "AdviceService.CreateAdvices", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *adviceServiceClient) GetAdvices(ctx context.Context, req *emptypb.Empty, opts ...client.CallOption) (*_go.GetAdvicesResponse, error) {
	rsp := &_go.GetAdvicesResponse{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "AdviceService.GetAdvices", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *adviceServiceClient) AddVote(ctx context.Context, req *_go.AddVoteRequest, opts ...client.CallOption) (*_go.AddVoteResponse, error) {
	rsp := &_go.AddVoteResponse{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "AdviceService.AddVote", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *adviceServiceClient) SetReferral(ctx context.Context, req *_go.SetReferralRequest, opts ...client.CallOption) (*emptypb.Empty, error) {
	rsp := &emptypb.Empty{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "AdviceService.SetReferral", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

type adviceServiceServer struct {
	_go.AdviceServiceServer
}

func (h *adviceServiceServer) CreateAdvices(ctx context.Context, req *_go.CreateAdvicesRequest, rsp *emptypb.Empty) error {
	return h.AdviceServiceServer.CreateAdvices(ctx, req, rsp)
}

func (h *adviceServiceServer) GetAdvices(ctx context.Context, req *emptypb.Empty, rsp *_go.GetAdvicesResponse) error {
	return h.AdviceServiceServer.GetAdvices(ctx, req, rsp)
}

func (h *adviceServiceServer) AddVote(ctx context.Context, req *_go.AddVoteRequest, rsp *_go.AddVoteResponse) error {
	return h.AdviceServiceServer.AddVote(ctx, req, rsp)
}

func (h *adviceServiceServer) SetReferral(ctx context.Context, req *_go.SetReferralRequest, rsp *emptypb.Empty) error {
	return h.AdviceServiceServer.SetReferral(ctx, req, rsp)
}

func RegisterAdviceServiceServer(s server.Server, sh _go.AdviceServiceServer, opts ...server.HandlerOption) error {
	type adviceService interface {
		CreateAdvices(ctx context.Context, req *_go.CreateAdvicesRequest, rsp *emptypb.Empty) error
		GetAdvices(ctx context.Context, req *emptypb.Empty, rsp *_go.GetAdvicesResponse) error
		AddVote(ctx context.Context, req *_go.AddVoteRequest, rsp *_go.AddVoteResponse) error
		SetReferral(ctx context.Context, req *_go.SetReferralRequest, rsp *emptypb.Empty) error
	}
	type AdviceService struct {
		adviceService
	}
	h := &adviceServiceServer{sh}
	return s.Handle(s.NewHandler(&AdviceService{h}, opts...))
}
