// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// protoc-gen-go-micro version: v3.10.15
// source: voteService.proto

package advicepb

import (
	context "context"
	_go "github.com/megauspexx/petsvote.last-proto/go"
	client "go.unistack.org/micro/v3/client"
	server "go.unistack.org/micro/v3/server"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

type voteServiceClient struct {
	c    client.Client
	name string
}

func NewVoteServiceClient(name string, c client.Client) _go.VoteServiceClient {
	return &voteServiceClient{c: c, name: name}
}

func (c *voteServiceClient) AddVote(ctx context.Context, req *_go.AddVoteRequest, opts ...client.CallOption) (*_go.AddVoteResponse, error) {
	rsp := &_go.AddVoteResponse{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "VoteService.AddVote", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *voteServiceClient) SetReferral(ctx context.Context, req *_go.SetReferralRequest, opts ...client.CallOption) (*emptypb.Empty, error) {
	rsp := &emptypb.Empty{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "VoteService.SetReferral", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

type voteServiceServer struct {
	_go.VoteServiceServer
}

func (h *voteServiceServer) AddVote(ctx context.Context, req *_go.AddVoteRequest, rsp *_go.AddVoteResponse) error {
	return h.VoteServiceServer.AddVote(ctx, req, rsp)
}

func (h *voteServiceServer) SetReferral(ctx context.Context, req *_go.SetReferralRequest, rsp *emptypb.Empty) error {
	return h.VoteServiceServer.SetReferral(ctx, req, rsp)
}

func RegisterVoteServiceServer(s server.Server, sh _go.VoteServiceServer, opts ...server.HandlerOption) error {
	type voteService interface {
		AddVote(ctx context.Context, req *_go.AddVoteRequest, rsp *_go.AddVoteResponse) error
		SetReferral(ctx context.Context, req *_go.SetReferralRequest, rsp *emptypb.Empty) error
	}
	type VoteService struct {
		voteService
	}
	h := &voteServiceServer{sh}
	return s.Handle(s.NewHandler(&VoteService{h}, opts...))
}
