// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v6.33.0
// source: addVote.proto

package advicepb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на добавление голоса
type AddVoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID пользователя, который голосует
	FromUserId int64 `protobuf:"varint,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	// ID питомца, за которого голосуют
	ToPetId int64 `protobuf:"varint,2,opt,name=to_pet_id,json=toPetId,proto3" json:"to_pet_id,omitempty"`
	// Оценка (1-5)
	Mark int32 `protobuf:"varint,3,opt,name=mark,proto3" json:"mark,omitempty"`
	// Флаг первого голосования пользователя
	FirstVote bool `protobuf:"varint,4,opt,name=first_vote,json=firstVote,proto3" json:"first_vote,omitempty"`
	// Флаг начисления очков без питомца
	GrantPoint bool `protobuf:"varint,5,opt,name=grant_point,json=grantPoint,proto3" json:"grant_point,omitempty"`
}

func (x *AddVoteRequest) Reset() {
	*x = AddVoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_addVote_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVoteRequest) ProtoMessage() {}

func (x *AddVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_addVote_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVoteRequest.ProtoReflect.Descriptor instead.
func (*AddVoteRequest) Descriptor() ([]byte, []int) {
	return file_addVote_proto_rawDescGZIP(), []int{0}
}

func (x *AddVoteRequest) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *AddVoteRequest) GetToPetId() int64 {
	if x != nil {
		return x.ToPetId
	}
	return 0
}

func (x *AddVoteRequest) GetMark() int32 {
	if x != nil {
		return x.Mark
	}
	return 0
}

func (x *AddVoteRequest) GetFirstVote() bool {
	if x != nil {
		return x.FirstVote
	}
	return false
}

func (x *AddVoteRequest) GetGrantPoint() bool {
	if x != nil {
		return x.GrantPoint
	}
	return false
}

var File_addVote_proto protoreflect.FileDescriptor

var file_addVote_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x64, 0x64, 0x56, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x1d, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x65, 0x74, 0x73, 0x76, 0x6f, 0x74, 0x65, 0x2e, 0x61, 0x64, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x17,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb6, 0x01, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x56,
	0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x0c, 0x66, 0x72,
	0x6f, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x09, 0x74, 0x6f, 0x5f, 0x70, 0x65, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x6f, 0x50, 0x65, 0x74, 0x49,
	0x64, 0x12, 0x1d, 0x0a, 0x04, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x42,
	0x09, 0xfa, 0x42, 0x06, 0x1a, 0x04, 0x18, 0x05, 0x28, 0x01, 0x52, 0x04, 0x6d, 0x61, 0x72, 0x6b,
	0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x76, 0x6f, 0x74, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x56, 0x6f, 0x74, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d,
	0x65, 0x67, 0x61, 0x75, 0x73, 0x70, 0x65, 0x78, 0x78, 0x2f, 0x70, 0x65, 0x74, 0x73, 0x76, 0x6f,
	0x74, 0x65, 0x2e, 0x6c, 0x61, 0x73, 0x74, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f,
	0x3b, 0x61, 0x64, 0x76, 0x69, 0x63, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_addVote_proto_rawDescOnce sync.Once
	file_addVote_proto_rawDescData = file_addVote_proto_rawDesc
)

func file_addVote_proto_rawDescGZIP() []byte {
	file_addVote_proto_rawDescOnce.Do(func() {
		file_addVote_proto_rawDescData = protoimpl.X.CompressGZIP(file_addVote_proto_rawDescData)
	})
	return file_addVote_proto_rawDescData
}

var file_addVote_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_addVote_proto_goTypes = []interface{}{
	(*AddVoteRequest)(nil), // 0: communication.petsvote.advice.AddVoteRequest
}
var file_addVote_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_addVote_proto_init() }
func file_addVote_proto_init() {
	if File_addVote_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_addVote_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddVoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_addVote_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_addVote_proto_goTypes,
		DependencyIndexes: file_addVote_proto_depIdxs,
		MessageInfos:      file_addVote_proto_msgTypes,
	}.Build()
	File_addVote_proto = out.File
	file_addVote_proto_rawDesc = nil
	file_addVote_proto_goTypes = nil
	file_addVote_proto_depIdxs = nil
}
