// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: addVote.proto

package advicepb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AddVoteRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddVoteRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddVoteRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddVoteRequestMultiError,
// or nil if none found.
func (m *AddVoteRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AddVoteRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetFromUserId() <= 0 {
		err := AddVoteRequestValidationError{
			field:  "FromUserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for ToPetId

	if val := m.GetMark(); val < 1 || val > 5 {
		err := AddVoteRequestValidationError{
			field:  "Mark",
			reason: "value must be inside range [1, 5]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for FirstVote

	// no validation rules for GrantPoint

	if len(errors) > 0 {
		return AddVoteRequestMultiError(errors)
	}

	return nil
}

// AddVoteRequestMultiError is an error wrapping multiple validation errors
// returned by AddVoteRequest.ValidateAll() if the designated constraints
// aren't met.
type AddVoteRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddVoteRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddVoteRequestMultiError) AllErrors() []error { return m }

// AddVoteRequestValidationError is the validation error returned by
// AddVoteRequest.Validate if the designated constraints aren't met.
type AddVoteRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddVoteRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddVoteRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddVoteRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddVoteRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddVoteRequestValidationError) ErrorName() string { return "AddVoteRequestValidationError" }

// Error satisfies the builtin error interface
func (e AddVoteRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddVoteRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddVoteRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddVoteRequestValidationError{}
