// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v6.33.0
// source: commonAdvice.proto

package advicepb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LangBy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kk string `protobuf:"bytes,1,opt,name=kk,proto3" json:"kk,omitempty"`
	Ru string `protobuf:"bytes,2,opt,name=ru,proto3" json:"ru,omitempty"`
	En string `protobuf:"bytes,3,opt,name=en,proto3" json:"en,omitempty"`
}

func (x *LangBy) Reset() {
	*x = LangBy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commonAdvice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LangBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LangBy) ProtoMessage() {}

func (x *LangBy) ProtoReflect() protoreflect.Message {
	mi := &file_commonAdvice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LangBy.ProtoReflect.Descriptor instead.
func (*LangBy) Descriptor() ([]byte, []int) {
	return file_commonAdvice_proto_rawDescGZIP(), []int{0}
}

func (x *LangBy) GetKk() string {
	if x != nil {
		return x.Kk
	}
	return ""
}

func (x *LangBy) GetRu() string {
	if x != nil {
		return x.Ru
	}
	return ""
}

func (x *LangBy) GetEn() string {
	if x != nil {
		return x.En
	}
	return ""
}

var File_commonAdvice_proto protoreflect.FileDescriptor

var file_commonAdvice_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x41, 0x64, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x65, 0x74, 0x73, 0x76, 0x6f, 0x74, 0x65, 0x2e, 0x61, 0x64, 0x76,
	0x69, 0x63, 0x65, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x53, 0x0a, 0x06,
	0x4c, 0x61, 0x6e, 0x67, 0x42, 0x79, 0x12, 0x17, 0x0a, 0x02, 0x6b, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x02, 0x6b, 0x6b, 0x12,
	0x17, 0x0a, 0x02, 0x72, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04,
	0x72, 0x02, 0x10, 0x01, 0x52, 0x02, 0x72, 0x75, 0x12, 0x17, 0x0a, 0x02, 0x65, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x02, 0x65,
	0x6e, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6d, 0x65, 0x67, 0x61, 0x75, 0x73, 0x70, 0x65, 0x78, 0x78, 0x2f, 0x70, 0x65, 0x74, 0x73, 0x76,
	0x6f, 0x74, 0x65, 0x2e, 0x6c, 0x61, 0x73, 0x74, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67,
	0x6f, 0x3b, 0x61, 0x64, 0x76, 0x69, 0x63, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_commonAdvice_proto_rawDescOnce sync.Once
	file_commonAdvice_proto_rawDescData = file_commonAdvice_proto_rawDesc
)

func file_commonAdvice_proto_rawDescGZIP() []byte {
	file_commonAdvice_proto_rawDescOnce.Do(func() {
		file_commonAdvice_proto_rawDescData = protoimpl.X.CompressGZIP(file_commonAdvice_proto_rawDescData)
	})
	return file_commonAdvice_proto_rawDescData
}

var file_commonAdvice_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_commonAdvice_proto_goTypes = []interface{}{
	(*LangBy)(nil), // 0: communication.petsvote.advice.LangBy
}
var file_commonAdvice_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_commonAdvice_proto_init() }
func file_commonAdvice_proto_init() {
	if File_commonAdvice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_commonAdvice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LangBy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_commonAdvice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commonAdvice_proto_goTypes,
		DependencyIndexes: file_commonAdvice_proto_depIdxs,
		MessageInfos:      file_commonAdvice_proto_msgTypes,
	}.Build()
	File_commonAdvice_proto = out.File
	file_commonAdvice_proto_rawDesc = nil
	file_commonAdvice_proto_goTypes = nil
	file_commonAdvice_proto_depIdxs = nil
}
