// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: commonAdvice.proto

package advicepb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on LangBy with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LangBy) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LangBy with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in LangByMultiError, or nil if none found.
func (m *LangBy) ValidateAll() error {
	return m.validate(true)
}

func (m *LangBy) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetKk()) < 1 {
		err := LangByValidationError{
			field:  "Kk",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetRu()) < 1 {
		err := LangByValidationError{
			field:  "Ru",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetEn()) < 1 {
		err := LangByValidationError{
			field:  "En",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return LangByMultiError(errors)
	}

	return nil
}

// LangByMultiError is an error wrapping multiple validation errors returned by
// LangBy.ValidateAll() if the designated constraints aren't met.
type LangByMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LangByMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LangByMultiError) AllErrors() []error { return m }

// LangByValidationError is the validation error returned by LangBy.Validate if
// the designated constraints aren't met.
type LangByValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LangByValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LangByValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LangByValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LangByValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LangByValidationError) ErrorName() string { return "LangByValidationError" }

// Error satisfies the builtin error interface
func (e LangByValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLangBy.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LangByValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LangByValidationError{}
