// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: createAdvices.proto

package advicepb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateAdvicesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateAdvicesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateAdvicesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateAdvicesRequestMultiError, or nil if none found.
func (m *CreateAdvicesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateAdvicesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetExternalId()) < 1 {
		err := CreateAdvicesRequestValidationError{
			field:  "ExternalId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetAdvices()) < 1 {
		err := CreateAdvicesRequestValidationError{
			field:  "Advices",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetAdvices() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CreateAdvicesRequestValidationError{
						field:  fmt.Sprintf("Advices[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CreateAdvicesRequestValidationError{
						field:  fmt.Sprintf("Advices[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CreateAdvicesRequestValidationError{
					field:  fmt.Sprintf("Advices[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return CreateAdvicesRequestMultiError(errors)
	}

	return nil
}

// CreateAdvicesRequestMultiError is an error wrapping multiple validation
// errors returned by CreateAdvicesRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateAdvicesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateAdvicesRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateAdvicesRequestMultiError) AllErrors() []error { return m }

// CreateAdvicesRequestValidationError is the validation error returned by
// CreateAdvicesRequest.Validate if the designated constraints aren't met.
type CreateAdvicesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateAdvicesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateAdvicesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateAdvicesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateAdvicesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateAdvicesRequestValidationError) ErrorName() string {
	return "CreateAdvicesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateAdvicesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateAdvicesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateAdvicesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateAdvicesRequestValidationError{}

// Validate checks the field values on ClientAdvices with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ClientAdvices) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ClientAdvices with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ClientAdvicesMultiError, or
// nil if none found.
func (m *ClientAdvices) ValidateAll() error {
	return m.validate(true)
}

func (m *ClientAdvices) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTitle()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ClientAdvicesValidationError{
					field:  "Title",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ClientAdvicesValidationError{
					field:  "Title",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTitle()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ClientAdvicesValidationError{
				field:  "Title",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetContent() == nil {
		err := ClientAdvicesValidationError{
			field:  "Content",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetContent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ClientAdvicesValidationError{
					field:  "Content",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ClientAdvicesValidationError{
					field:  "Content",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetContent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ClientAdvicesValidationError{
				field:  "Content",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetButton()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ClientAdvicesValidationError{
					field:  "Button",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ClientAdvicesValidationError{
					field:  "Button",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetButton()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ClientAdvicesValidationError{
				field:  "Button",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetExpiresAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ClientAdvicesValidationError{
					field:  "ExpiresAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ClientAdvicesValidationError{
					field:  "ExpiresAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExpiresAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ClientAdvicesValidationError{
				field:  "ExpiresAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if utf8.RuneCountInString(m.GetScreen()) < 1 {
		err := ClientAdvicesValidationError{
			field:  "Screen",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ClientAdvicesMultiError(errors)
	}

	return nil
}

// ClientAdvicesMultiError is an error wrapping multiple validation errors
// returned by ClientAdvices.ValidateAll() if the designated constraints
// aren't met.
type ClientAdvicesMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ClientAdvicesMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ClientAdvicesMultiError) AllErrors() []error { return m }

// ClientAdvicesValidationError is the validation error returned by
// ClientAdvices.Validate if the designated constraints aren't met.
type ClientAdvicesValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ClientAdvicesValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ClientAdvicesValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ClientAdvicesValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ClientAdvicesValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ClientAdvicesValidationError) ErrorName() string { return "ClientAdvicesValidationError" }

// Error satisfies the builtin error interface
func (e ClientAdvicesValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sClientAdvices.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ClientAdvicesValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ClientAdvicesValidationError{}

// Validate checks the field values on Button with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Button) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Button with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ButtonMultiError, or nil if none found.
func (m *Button) ValidateAll() error {
	return m.validate(true)
}

func (m *Button) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetText()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ButtonValidationError{
					field:  "Text",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ButtonValidationError{
					field:  "Text",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetText()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ButtonValidationError{
				field:  "Text",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetLink()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ButtonValidationError{
					field:  "Link",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ButtonValidationError{
					field:  "Link",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLink()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ButtonValidationError{
				field:  "Link",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ButtonMultiError(errors)
	}

	return nil
}

// ButtonMultiError is an error wrapping multiple validation errors returned by
// Button.ValidateAll() if the designated constraints aren't met.
type ButtonMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ButtonMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ButtonMultiError) AllErrors() []error { return m }

// ButtonValidationError is the validation error returned by Button.Validate if
// the designated constraints aren't met.
type ButtonValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ButtonValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ButtonValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ButtonValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ButtonValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ButtonValidationError) ErrorName() string { return "ButtonValidationError" }

// Error satisfies the builtin error interface
func (e ButtonValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sButton.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ButtonValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ButtonValidationError{}
