// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v6.33.0
// source: getAdvices.proto

package advicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAdvicesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Advices []*Advices `protobuf:"bytes,1,rep,name=advices,proto3" json:"advices,omitempty"`
}

func (x *GetAdvicesResponse) Reset() {
	*x = GetAdvicesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getAdvices_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAdvicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdvicesResponse) ProtoMessage() {}

func (x *GetAdvicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_getAdvices_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdvicesResponse.ProtoReflect.Descriptor instead.
func (*GetAdvicesResponse) Descriptor() ([]byte, []int) {
	return file_getAdvices_proto_rawDescGZIP(), []int{0}
}

func (x *GetAdvicesResponse) GetAdvices() []*Advices {
	if x != nil {
		return x.Advices
	}
	return nil
}

type Advices struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Screen   string  `protobuf:"bytes,1,opt,name=screen,proto3" json:"screen,omitempty"`
	Content  *LangBy `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	DeepLink *LangBy `protobuf:"bytes,3,opt,name=deep_link,json=deepLink,proto3" json:"deep_link,omitempty"`
}

func (x *Advices) Reset() {
	*x = Advices{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getAdvices_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Advices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Advices) ProtoMessage() {}

func (x *Advices) ProtoReflect() protoreflect.Message {
	mi := &file_getAdvices_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Advices.ProtoReflect.Descriptor instead.
func (*Advices) Descriptor() ([]byte, []int) {
	return file_getAdvices_proto_rawDescGZIP(), []int{1}
}

func (x *Advices) GetScreen() string {
	if x != nil {
		return x.Screen
	}
	return ""
}

func (x *Advices) GetContent() *LangBy {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Advices) GetDeepLink() *LangBy {
	if x != nil {
		return x.DeepLink
	}
	return nil
}

var File_getAdvices_proto protoreflect.FileDescriptor

var file_getAdvices_proto_rawDesc = []byte{
	0x0a, 0x10, 0x67, 0x65, 0x74, 0x41, 0x64, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x1d, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x65, 0x74, 0x73, 0x76, 0x6f, 0x74, 0x65, 0x2e, 0x61, 0x64, 0x76, 0x69, 0x63,
	0x65, 0x1a, 0x12, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x41, 0x64, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x56, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x64, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x07, 0x61,
	0x64, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x65, 0x74,
	0x73, 0x76, 0x6f, 0x74, 0x65, 0x2e, 0x61, 0x64, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x64, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x52, 0x07, 0x61, 0x64, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0xa6, 0x01,
	0x0a, 0x07, 0x41, 0x64, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x72,
	0x65, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x72, 0x65, 0x65,
	0x6e, 0x12, 0x3f, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x25, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x65, 0x74, 0x73, 0x76, 0x6f, 0x74, 0x65, 0x2e, 0x61, 0x64, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x42, 0x79, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x42, 0x0a, 0x09, 0x64, 0x65, 0x65, 0x70, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x65, 0x74, 0x73, 0x76, 0x6f, 0x74, 0x65, 0x2e, 0x61,
	0x64, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x42, 0x79, 0x52, 0x08, 0x64, 0x65,
	0x65, 0x70, 0x4c, 0x69, 0x6e, 0x6b, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x67, 0x61, 0x75, 0x73, 0x70, 0x65, 0x78, 0x78, 0x2f,
	0x70, 0x65, 0x74, 0x73, 0x76, 0x6f, 0x74, 0x65, 0x2e, 0x6c, 0x61, 0x73, 0x74, 0x2d, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x3b, 0x61, 0x64, 0x76, 0x69, 0x63, 0x65, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_getAdvices_proto_rawDescOnce sync.Once
	file_getAdvices_proto_rawDescData = file_getAdvices_proto_rawDesc
)

func file_getAdvices_proto_rawDescGZIP() []byte {
	file_getAdvices_proto_rawDescOnce.Do(func() {
		file_getAdvices_proto_rawDescData = protoimpl.X.CompressGZIP(file_getAdvices_proto_rawDescData)
	})
	return file_getAdvices_proto_rawDescData
}

var file_getAdvices_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_getAdvices_proto_goTypes = []interface{}{
	(*GetAdvicesResponse)(nil), // 0: communication.petsvote.advice.GetAdvicesResponse
	(*Advices)(nil),            // 1: communication.petsvote.advice.Advices
	(*LangBy)(nil),             // 2: communication.petsvote.advice.LangBy
}
var file_getAdvices_proto_depIdxs = []int32{
	1, // 0: communication.petsvote.advice.GetAdvicesResponse.advices:type_name -> communication.petsvote.advice.Advices
	2, // 1: communication.petsvote.advice.Advices.content:type_name -> communication.petsvote.advice.LangBy
	2, // 2: communication.petsvote.advice.Advices.deep_link:type_name -> communication.petsvote.advice.LangBy
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_getAdvices_proto_init() }
func file_getAdvices_proto_init() {
	if File_getAdvices_proto != nil {
		return
	}
	file_commonAdvice_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_getAdvices_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAdvicesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_getAdvices_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Advices); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_getAdvices_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_getAdvices_proto_goTypes,
		DependencyIndexes: file_getAdvices_proto_depIdxs,
		MessageInfos:      file_getAdvices_proto_msgTypes,
	}.Build()
	File_getAdvices_proto = out.File
	file_getAdvices_proto_rawDesc = nil
	file_getAdvices_proto_goTypes = nil
	file_getAdvices_proto_depIdxs = nil
}
